version: '3'
services:
 web:
  container_name: dev
  image: "bhanuprakashece410/wildfly"
  ports:
  - "8080:8080"
  volumes:
  - ./sanity:/var/log/sanity
  restart: always
  command: -Djboss.server.log.dir=/var/log/sanity
  depends_on:
    - redis
 redis:
  container_name: devdb
  image: "redis:alpine"
  ports:
  - "6379:6379"
